#include <exception>
#include <QDebug>
#include <QFile>
#include <QGuiApplication>
#include <QHostAddress>
#include <QMetaObject>
#include <QNetworkAddressEntry>
#include <QNetworkDatagram>
#include <QNetworkInterface>
#include <QQmlApplicationEngine>
#include <QTimer>
#include <QUdpSocket>
#include <QUrl>
#include <QVariantMap>
#include <type_traits>
